[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    'test/=test/',
    '@openzeppelin/contracts=../../../node_modules/@openzeppelin/contracts/',
    '@ngquests/contracts/=../../../node_modules/@ngquests/contracts/'
]

[rpc_endpoints]
localhost = 'http://localhost:8545'